Comment out validate chart to test on PR

diff --git a/.github/workflows/gha-bump-and-publish-charts.yaml b/.github/workflows/gha-bump-and-publish-charts.yaml
--- a/.github/workflows/gha-bump-and-publish-charts.yaml
+++ b/.github/workflows/gha-bump-and-publish-charts.yaml
@@ -42,13 +42,13 @@ jobs:
         with:
           ref: ${{ inputs.ref }}
 
-      - name: Validate version format
-        run: |
-          VERSION="${{ inputs.new_version }}"
-          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format. Must be in format X.Y.Z"
-            exit 1
-          fi
+      # - name: Validate version format
+      #   run: |
+      #     VERSION="${{ inputs.new_version }}"
+      #     if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+      #       echo "Invalid version format. Must be in format X.Y.Z"
+      #       exit 1
+      #     fi
 
   update-chart-versions:
     needs: validate-version
diff --git a/.github/workflows/publish-helm-charts.yaml b/.github/workflows/publish-helm-charts.yaml
--- a/.github/workflows/publish-helm-charts.yaml
+++ b/.github/workflows/publish-helm-charts.yaml
@@ -47,13 +47,13 @@ jobs:
         with:
           version: ${{ env.HELM_VERSION }}
 
-      - name: Validate version format
-        run: |
-          VERSION="${{ inputs.new_version }}"
-          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format. Must be in format X.Y.Z"
-            exit 1
-          fi
+      # - name: Validate version format
+      #   run: |
+      #     VERSION="${{ inputs.new_version }}"
+      #     if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+      #       echo "Invalid version format. Must be in format X.Y.Z"
+      #       exit 1
+      #     fi
 
       - name: Lint Controller Chart
         run: helm lint charts/gha-runner-scale-set-controller/
